### PR TITLE
deps: updated firebase dependencies

### LINKED ISSUE #21: Please update dependencies
@rrousselGit 

Could you please update the dependencies listed in the [dependencies](https://github.com/FirebaseExtended/firestoreodm-flutter/blob/main/packages/cloud_firestore_odm/pubspec.yaml#L14C3-L14C18)?

### PR DESCRIPTION
**Pull request by dorklein**
Updated dependencies to work with cloud_firestore: ^5.0.0 & firebase_core: ^3.0.0

Fixes #21

> It's a good idea to open an issue first for discussion.

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by fatihsever** [comment]
+1

**Comment by ivatar39** [comment]
@rrousselGit any updates on this?

**Comment by cuong0993** [comment]
Guess we can do like this while waiting as always

```
dependency_overrides:
  cloud_firestore_odm:
    git:
      path: packages/cloud_firestore_odm
      url: https://github.com/dorklein/firestoreodm-flutter.git
  cloud_firestore_odm_generator:
    git:
      path: packages/cloud_firestore_odm_generator
      url: https://github.com/dorklein/firestoreodm-flutter.git
```

**Comment by dorklein** [comment]
Exactly what I'm doing meanwhile

**Comment by motucraft** [comment]
What is this pull request waiting for? Is the package not maintained?

**Comment by rrousselGit** [comment]
Well I'm in holidays...

Anyway I have a bit of time today. Let me make a quick release

**Pull request merged**
