### PR TITLE
Add batch API

### PR DESCRIPTION
**Pull request by lirantzairi**
I added a convenient API for using batch operations similar to the transaction API.

### CODE REVIEW

**Comment by rrousselGit** [comment]
LGTM!

Do you mind updating the changelog?

**Comment by lirantzairi** [comment]
@rrousselGit Sure, I also added a corresponding issue that this PR fixes: https://github.com/FirebaseExtended/firestoreodm-flutter/issues/12

**Comment by lirantzairi** [comment]
@rrousselGit done

**Comment by rrousselGit** [comment]
Thanks again!

**Pull request merged**
